languageCode = "en-us"
title = "Come Up With a Title"
baseURL = "http://nolanprice.com"
theme = "beautifulhugo"
paginate = 5
copyright = "Copyright (c) 2017 - 2017, Nolan Price; all rights reserved."
googleAnalytics = "UA-92866629-1"
disqusShortname = "nolan-blog"

  # Theme variables
  [params]
    # Site author
    author = "Nolan Price"
    subtitle = "Learn about stuff from some guy who hates words"
    logo = "img/Nolan_Price_Square.jpg"
    favicon = "img/favicon.ico"
    commit = false
    name = "Nolan Price"
    email = "nolan@nolanprice.com"
    github = "nprice1"
    linkedin = "nolan-price-3a630381"
    kaggle = "nprice"

  [[menu.main]]
      name = "Blog"
      url = "/"
      weight = 1

  [[menu.main]]
      name = "About"
      url = "/page/about"
      weight = 2
